// Code generated by protoc-gen-go.
// source: model/command.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model/command.proto

It has these top-level messages:
	Message
	Response
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Commands int32

const (
	Message_status  Message_Commands = 0
	Message_start   Message_Commands = 1
	Message_stop    Message_Commands = 2
	Message_restart Message_Commands = 3
	Message_reload  Message_Commands = 4
)

var Message_Commands_name = map[int32]string{
	0: "status",
	1: "start",
	2: "stop",
	3: "restart",
	4: "reload",
}
var Message_Commands_value = map[string]int32{
	"status":  0,
	"start":   1,
	"stop":    2,
	"restart": 3,
	"reload":  4,
}

func (x Message_Commands) Enum() *Message_Commands {
	p := new(Message_Commands)
	*p = x
	return p
}
func (x Message_Commands) String() string {
	return proto.EnumName(Message_Commands_name, int32(x))
}
func (x *Message_Commands) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Commands_value, data, "Message_Commands")
	if err != nil {
		return err
	}
	*x = Message_Commands(value)
	return nil
}
func (Message_Commands) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Response_Codes int32

const (
	Response_success     Response_Codes = 0
	Response_suc_reload  Response_Codes = 1
	Response_suc_status  Response_Codes = 2
	Response_suc_start   Response_Codes = 3
	Response_suc_stop    Response_Codes = 4
	Response_suc_restart Response_Codes = 5
	Response_error       Response_Codes = 100
	Response_err_missing Response_Codes = 101
	Response_err_parsing Response_Codes = 102
	Response_err_reading Response_Codes = 103
	Response_err_cmd     Response_Codes = 104
	Response_err_status  Response_Codes = 105
	Response_err_start   Response_Codes = 106
	Response_err_stop    Response_Codes = 107
	Response_err_restart Response_Codes = 108
	Response_err_reload  Response_Codes = 109
)

var Response_Codes_name = map[int32]string{
	0:   "success",
	1:   "suc_reload",
	2:   "suc_status",
	3:   "suc_start",
	4:   "suc_stop",
	5:   "suc_restart",
	100: "error",
	101: "err_missing",
	102: "err_parsing",
	103: "err_reading",
	104: "err_cmd",
	105: "err_status",
	106: "err_start",
	107: "err_stop",
	108: "err_restart",
	109: "err_reload",
}
var Response_Codes_value = map[string]int32{
	"success":     0,
	"suc_reload":  1,
	"suc_status":  2,
	"suc_start":   3,
	"suc_stop":    4,
	"suc_restart": 5,
	"error":       100,
	"err_missing": 101,
	"err_parsing": 102,
	"err_reading": 103,
	"err_cmd":     104,
	"err_status":  105,
	"err_start":   106,
	"err_stop":    107,
	"err_restart": 108,
	"err_reload":  109,
}

func (x Response_Codes) Enum() *Response_Codes {
	p := new(Response_Codes)
	*p = x
	return p
}
func (x Response_Codes) String() string {
	return proto.EnumName(Response_Codes_name, int32(x))
}
func (x *Response_Codes) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Codes_value, data, "Response_Codes")
	if err != nil {
		return err
	}
	*x = Response_Codes(value)
	return nil
}
func (Response_Codes) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Message struct {
	Service          *string           `protobuf:"bytes,1,req,name=Service" json:"Service,omitempty"`
	Command          *Message_Commands `protobuf:"varint,2,req,name=Command,enum=model.Message_Commands" json:"Command,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *Message) GetCommand() Message_Commands {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return Message_status
}

type Response struct {
	Code             *Response_Codes `protobuf:"varint,1,req,name=Code,enum=model.Response_Codes" json:"Code,omitempty"`
	Message          *string         `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetCode() Response_Codes {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return Response_success
}

func (m *Response) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "model.Message")
	proto.RegisterType((*Response)(nil), "model.Response")
	proto.RegisterEnum("model.Message_Commands", Message_Commands_name, Message_Commands_value)
	proto.RegisterEnum("model.Response_Codes", Response_Codes_name, Response_Codes_value)
}

func init() { proto.RegisterFile("model/command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8f, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x49, 0x48, 0x48, 0x32, 0x85, 0x62, 0x19, 0x21, 0xba, 0x44, 0x61, 0xd3, 0x55, 0x90,
	0x7a, 0x85, 0xb2, 0x65, 0x03, 0x07, 0xa8, 0xa2, 0x64, 0x28, 0x81, 0xba, 0x8e, 0x3c, 0x29, 0x87,
	0xe0, 0x50, 0x5c, 0x8c, 0x0d, 0x33, 0xb1, 0x2d, 0x76, 0xf3, 0xff, 0xcf, 0xcf, 0x7f, 0x86, 0x1b,
	0x63, 0x7b, 0x3c, 0x3c, 0x76, 0xd6, 0x98, 0xf6, 0xd8, 0x37, 0xa3, 0xb3, 0x93, 0xd5, 0xf9, 0x6c,
	0xd6, 0xdf, 0x09, 0x14, 0xcf, 0x48, 0xd4, 0xee, 0x51, 0x5f, 0x43, 0xf1, 0x8a, 0xee, 0x6b, 0xe8,
	0x70, 0x95, 0xdc, 0xa7, 0xeb, 0x4a, 0xaf, 0xa1, 0xd8, 0xfa, 0xd2, 0x2a, 0x65, 0x63, 0xb9, 0xb9,
	0x6b, 0xe6, 0x56, 0x13, 0x1a, 0x4d, 0x48, 0xa9, 0x7e, 0x82, 0x32, 0xde, 0x1a, 0xe0, 0x82, 0xa6,
	0x76, 0x3a, 0x91, 0x3a, 0xd3, 0x15, 0xe4, 0x7c, 0xbb, 0x49, 0x25, 0xba, 0x84, 0x8c, 0x26, 0x3b,
	0xaa, 0x54, 0x2f, 0xa0, 0x70, 0xe8, 0xed, 0x73, 0xf9, 0xda, 0xe1, 0xc1, 0xb6, 0xbd, 0xca, 0xea,
	0x9f, 0x14, 0xca, 0x17, 0xa4, 0xd1, 0x1e, 0x09, 0xf5, 0x03, 0x64, 0x5b, 0x1e, 0x9b, 0x51, 0x96,
	0x9b, 0xdb, 0xb0, 0x1c, 0xe3, 0x46, 0x32, 0x12, 0xe4, 0xc0, 0xc2, 0x84, 0xc9, 0xba, 0xaa, 0x7f,
	0x13, 0xc8, 0x7d, 0xc4, 0x2b, 0x74, 0xea, 0x3a, 0x4e, 0x99, 0x63, 0x09, 0xc0, 0x62, 0x17, 0x96,
	0x92, 0xa8, 0x03, 0x67, 0xaa, 0xaf, 0xa0, 0x0a, 0x7a, 0x86, 0xba, 0x84, 0xd2, 0x4b, 0xe6, 0xcd,
	0x78, 0x64, 0xe1, 0xcb, 0x3e, 0xce, 0xe5, 0x55, 0xe8, 0x9c, 0x75, 0xaa, 0x97, 0x8c, 0xcf, 0x9d,
	0x19, 0x88, 0x86, 0xe3, 0x5e, 0x61, 0x34, 0xc6, 0xd6, 0xcd, 0xc6, 0x5b, 0x34, 0x1c, 0xb6, 0xbd,
	0x18, 0x7b, 0x01, 0x13, 0xa3, 0x33, 0xbd, 0x7a, 0x17, 0x10, 0x11, 0x01, 0x64, 0x10, 0x90, 0xa0,
	0x79, 0xe9, 0x43, 0x40, 0xbc, 0x64, 0x90, 0xcf, 0xff, 0x5f, 0xf9, 0xf8, 0x10, 0xdb, 0xe1, 0x59,
	0xe6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x55, 0xf6, 0x52, 0xf2, 0xea, 0x01, 0x00, 0x00,
}
