// Code generated by protoc-gen-go.
// source: restartd/service.proto
// DO NOT EDIT!

/*
Package restartd is a generated protocol buffer package.

It is generated from these files:
	restartd/service.proto

It has these top-level messages:
	Service
	Status
*/
package restartd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status_States int32

const (
	Status_started Status_States = 0
	Status_stopped Status_States = 1
	Status_failed  Status_States = 2
)

var Status_States_name = map[int32]string{
	0: "started",
	1: "stopped",
	2: "failed",
}
var Status_States_value = map[string]int32{
	"started": 0,
	"stopped": 1,
	"failed":  2,
}

func (x Status_States) String() string {
	return proto.EnumName(Status_States_name, int32(x))
}
func (Status_States) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Service struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	Status []*Status_State `protobuf:"bytes,1,rep,name=Status" json:"Status,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Status) GetStatus() []*Status_State {
	if m != nil {
		return m.Status
	}
	return nil
}

type Status_State struct {
	Name  string        `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	State Status_States `protobuf:"varint,2,opt,name=State,enum=restartd.Status_States" json:"State,omitempty"`
	Since int32         `protobuf:"varint,3,opt,name=Since" json:"Since,omitempty"`
}

func (m *Status_State) Reset()                    { *m = Status_State{} }
func (m *Status_State) String() string            { return proto.CompactTextString(m) }
func (*Status_State) ProtoMessage()               {}
func (*Status_State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func init() {
	proto.RegisterType((*Service)(nil), "restartd.Service")
	proto.RegisterType((*Status)(nil), "restartd.Status")
	proto.RegisterType((*Status_State)(nil), "restartd.Status.State")
	proto.RegisterEnum("restartd.Status_States", Status_States_name, Status_States_value)
}

func init() { proto.RegisterFile("restartd/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4a, 0x2d, 0x2e,
	0x49, 0x2c, 0x2a, 0x49, 0xd1, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x89, 0x2b, 0xc9, 0x72, 0xb1, 0x07, 0x43, 0xa4, 0x84, 0x84, 0xb8,
	0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0xa5, 0x53,
	0x8c, 0x5c, 0x6c, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x42, 0x7a, 0x30, 0x16, 0x50, 0x01, 0xb3,
	0x06, 0xb7, 0x91, 0x98, 0x1e, 0xcc, 0x10, 0x3d, 0x88, 0x38, 0x98, 0x4a, 0x0d, 0x82, 0xaa, 0x92,
	0x4a, 0xe0, 0x62, 0x05, 0x0b, 0x60, 0x33, 0x57, 0x48, 0x17, 0x2a, 0x29, 0xc1, 0x04, 0x14, 0xe4,
	0x33, 0x12, 0xc7, 0x6e, 0x56, 0x71, 0x10, 0xd4, 0x08, 0x11, 0xa0, 0xf2, 0xcc, 0xbc, 0xe4, 0x54,
	0x09, 0x66, 0xa0, 0x72, 0xd6, 0x20, 0x08, 0x47, 0x09, 0xea, 0xa2, 0xd4, 0x62, 0x21, 0x6e, 0x2e,
	0x76, 0xb0, 0xf6, 0xd4, 0x14, 0x01, 0x06, 0x08, 0x27, 0xbf, 0xa0, 0x00, 0xc8, 0x61, 0x14, 0xe2,
	0xe2, 0x62, 0x4b, 0x4b, 0xcc, 0xcc, 0x01, 0xb2, 0x99, 0x8c, 0xac, 0xb9, 0x38, 0x82, 0xa0, 0xd6,
	0x08, 0xe9, 0x73, 0xb1, 0x15, 0x43, 0xfc, 0x25, 0x88, 0x64, 0x37, 0x24, 0x24, 0xa4, 0x04, 0xd0,
	0x9d, 0xa3, 0xc4, 0x90, 0xc4, 0x06, 0x0e, 0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0x8f, 0x52, 0x95, 0x53, 0x01, 0x00, 0x00,
}
